name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv pandas pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --exclude-module torch ^
                   --exclude-module torchvision ^
                   --exclude-module tensorflow ^
                   --exclude-module sklearn ^
                   --exclude-module scipy ^
                   --exclude-module PIL ^
                   --exclude-module matplotlib ^
                   --exclude-module transformers ^
                   --exclude-module IPython ^
                   --exclude-module jupyter ^
                   --exclude-module jedi ^
                   --exclude-module parso ^
                   --exclude-module pygments ^
                   --exclude-module fsspec ^
                   --exclude-module pydantic ^
                   --exclude-module jinja2 ^
                   --exclude-module regex ^
                   --exclude-module yt_dlp ^
                   --exclude-module mutagen ^
                   --exclude-module brotli ^
                   --exclude-module secretstorage ^
                   --exclude-module curl_cffi ^
                   --exclude-module certifi ^
                   --exclude-module urllib3 ^
                   --exclude-module requests ^
                   --exclude-module wcwidth ^
                   --exclude-module charset_normalizer ^
                   --exclude-module win32com ^
                   --onefile ^
                   read_file.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/read_file.exe