name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv pandas pyinstaller
    
    - name: Create PyInstaller spec file
      run: |
        echo "# -*- mode: python ; coding: utf-8 -*-" > read_file.spec
        echo "" >> read_file.spec
        echo "excludes = [" >> read_file.spec
        echo "    'torch', 'torchvision', 'tensorflow', 'sklearn', 'scipy'," >> read_file.spec
        echo "    'PIL', 'matplotlib', 'transformers', 'IPython', 'jupyter'," >> read_file.spec
        echo "    'jedi', 'parso', 'pygments', 'fsspec', 'pydantic'," >> read_file.spec
        echo "    'jinja2', 'regex', 'yt_dlp', 'mutagen', 'brotli'," >> read_file.spec
        echo "    'secretstorage', 'curl_cffi', 'certifi', 'urllib3'," >> read_file.spec
        echo "    'requests', 'wcwidth', 'charset_normalizer', 'win32com'" >> read_file.spec
        echo "]" >> read_file.spec
        echo "" >> read_file.spec
        echo "a = Analysis(" >> read_file.spec
        echo "    ['read_file.py']," >> read_file.spec
        echo "    pathex=[]," >> read_file.spec
        echo "    binaries=[]," >> read_file.spec
        echo "    datas=[]," >> read_file.spec
        echo "    hiddenimports=[]," >> read_file.spec
        echo "    hookspath=[]," >> read_file.spec
        echo "    hooksconfig={}," >> read_file.spec
        echo "    runtime_hooks=[]," >> read_file.spec
        echo "    excludes=excludes," >> read_file.spec
        echo "    noarchive=False," >> read_file.spec
        echo ")" >> read_file.spec
        echo "" >> read_file.spec
        echo "pyz = PYZ(a.pure, a.zipped_data)" >> read_file.spec
        echo "" >> read_file.spec
        echo "exe = EXE(" >> read_file.spec
        echo "    pyz," >> read_file.spec
        echo "    a.scripts," >> read_file.spec
        echo "    a.binaries," >> read_file.spec
        echo "    a.zipfiles," >> read_file.spec
        echo "    a.datas," >> read_file.spec
        echo "    []," >> read_file.spec
        echo "    name='read_file'," >> read_file.spec
        echo "    debug=False," >> read_file.spec
        echo "    bootloader_ignore_signals=False," >> read_file.spec
        echo "    strip=False," >> read_file.spec
        echo "    upx=True," >> read_file.spec
        echo "    console=True," >> read_file.spec
        echo ")" >> read_file.spec
    
    - name: Build executable
      run: pyinstaller read_file.spec
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/read_file.exe